In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('/content/Loan_Default.csv')

In [3]:
data

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148665,173555,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,...,CIB,659,EXP,55-64,to_inst,71.792763,south,direct,0,48.0
148666,173556,2019,cf,Male,nopre,type1,p1,l1,nopc,nob/c,...,CIB,569,CIB,25-34,not_inst,74.428934,south,direct,0,15.0
148667,173557,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,CIB,702,EXP,45-54,not_inst,61.332418,North,direct,0,49.0
148668,173558,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,...,EXP,737,EXP,55-64,to_inst,70.683453,North,direct,0,29.0
148669,173559,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,CIB,830,CIB,45-54,not_inst,72.849462,North,direct,0,44.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 34 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ID                         148670 non-null  int64
 1   year                       148670 non-null  int64
 2   loan_limit                 145326 non-null  object
 3   Gender                     148670 non-null  object
 4   approv_in_adv              147762 non-null  object
 5   loan_type                  148670 non-null  object
 6   loan_purpose               148536 non-null  object
 7   Credit_Worthiness          148670 non-null  object
 8   open_credit                148670 non-null  object
 9   business_or_commercial     148670 non-null  object
 10  loan_amount                148670 non-null  int64
 11  rate_of_interest           112231 non-null  float64
 12  Interest_rate_spread       112031 non-null  float64
 13  Upfront_charges            109028 non-null  float64
 14  term                       148629 non-null  float64
 15  Neg_ammortization          148549 non-null  object
 16  interest_only              148670 non-null  object
 17  lump_sum_payment           148670 non-null  object
 18  property_value             133572 non-null  float64
 19  construction_type          148670 non-null  object
 20  occupancy_type             148670 non-null  object
 21  Secured_by                 148670 non-null  object
 22  total_units                148670 non-null  object
 23  income                     139520 non-null  float64
 24  credit_type                148670 non-null  object
 25  Credit_Score               148670 non-null  int64
 26  co-applicant_credit_type   148670 non-null  object
 27  age                        148470 non-null  object
 28  submission_of_application  148470 non-null  object
 29  LTV                        133572 non-null  float64
 30  Region                     148670 non-null  object
 31  Security_Type              148670 non-null  object
 32  Status                     148670 non-null  int64
 33  dtir1                      124549 non-null  float64
dtypes: float64(8), int64(5), object(21)
memory usage: 38.6+ MB

In [5]:
data.isna().sum()

ID                               0
year                             0
loan_limit                    3344
Gender                           0
approv_in_adv                  908
loan_type                        0
loan_purpose                   134
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                            41
Neg_ammortization              121
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                        9150
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                            200
submission_of_application      200
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [6]:
data.columns

Index(['ID', 'year', 'loan_limit', 'Gender', 'approv_in_adv', 'loan_type',
       'loan_purpose', 'Credit_Worthiness', 'open_credit',
       'business_or_commercial', 'loan_amount', 'rate_of_interest',
       'Interest_rate_spread', 'Upfront_charges', 'term', 'Neg_ammortization',
       'interest_only', 'lump_sum_payment', 'property_value',
       'construction_type', 'occupancy_type', 'Secured_by', 'total_units',
       'income', 'credit_type', 'Credit_Score', 'co-applicant_credit_type',
       'age', 'submission_of_application', 'LTV', 'Region', 'Security_Type',
       'Status', 'dtir1'],
      dtype='object')

In [7]:
for col in ['rate_of_interest','Interest_rate_spread']:
       data[col]=data[col].fillna(data[col].mean())

In [8]:
for col in ['Upfront_charges','term','property_value','income','LTV','dtir1']:
       data[col]=data[col].fillna(data[col].median())

In [9]:
for col in ['loan_limit','approv_in_adv','loan_purpose','Neg_ammortization',
            'age','submission_of_application']:
  data[col]=data[col].fillna(data[col].mode()[0])

In [10]:
data.isna().sum()

ID                           0
year                         0
loan_limit                   0
Gender                       0
approv_in_adv                0
loan_type                    0
loan_purpose                 0
Credit_Worthiness            0
open_credit                  0
business_or_commercial       0
loan_amount                  0
rate_of_interest             0
Interest_rate_spread         0
Upfront_charges              0
term                         0
Neg_ammortization            0
interest_only                0
lump_sum_payment             0
property_value               0
construction_type            0
occupancy_type               0
Secured_by                   0
total_units                  0
income                       0
credit_type                  0
Credit_Score                 0
co-applicant_credit_type     0
age                          0
submission_of_application    0
LTV                          0
Region                       0
Security_Type                0
Status                       0
dtir1                        0
dtype: int64

In [11]:
data=data.drop(['ID','year','Interest_rate_spread','loan_amount'],axis=1)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 30 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   loan_limit                 148670 non-null  object
 1   Gender                     148670 non-null  object
 2   approv_in_adv              148670 non-null  object
 3   loan_type                  148670 non-null  object
 4   loan_purpose               148670 non-null  object
 5   Credit_Worthiness          148670 non-null  object
 6   open_credit                148670 non-null  object
 7   business_or_commercial     148670 non-null  object
 8   rate_of_interest           148670 non-null  float64
 9   Upfront_charges            148670 non-null  float64
 10  term                       148670 non-null  float64
 11  Neg_ammortization          148670 non-null  object
 12  interest_only              148670 non-null  object
 13  lump_sum_payment           148670 non-null  object
 14  property_value             148670 non-null  float64
 15  construction_type          148670 non-null  object
 16  occupancy_type             148670 non-null  object
 17  Secured_by                 148670 non-null  object
 18  total_units                148670 non-null  object
 19  income                     148670 non-null  float64
 20  credit_type                148670 non-null  object
 21  Credit_Score               148670 non-null  int64
 22  co-applicant_credit_type   148670 non-null  object
 23  age                        148670 non-null  object
 24  submission_of_application  148670 non-null  object
 25  LTV                        148670 non-null  float64
 26  Region                     148670 non-null  object
 27  Security_Type              148670 non-null  object
 28  Status                     148670 non-null  int64
 29  dtir1                      148670 non-null  float64
dtypes: float64(7), int64(2), object(21)
memory usage: 34.0+ MB

One Hot Encoding

In [13]:
data2=data.copy()

In [14]:
data2.nunique()

loan_limit                       2
Gender                           4
approv_in_adv                    2
loan_type                        3
loan_purpose                     4
Credit_Worthiness                2
open_credit                      2
business_or_commercial           2
rate_of_interest               132
Upfront_charges              58272
term                            26
Neg_ammortization                2
interest_only                    2
lump_sum_payment                 2
property_value                 385
construction_type                2
occupancy_type                   3
Secured_by                       2
total_units                      4
income                        1001
credit_type                      4
Credit_Score                   401
co-applicant_credit_type         2
age                              7
submission_of_application        2
LTV                           8484
Region                           4
Security_Type                    2
Status                           2
dtir1                           57
dtype: int64

In [15]:
for column in data.columns:
    unique_values = data[column].unique()
    print(f"Unique values in column '{column}': {unique_values}")

Unique values in column 'loan_limit': ['cf' 'ncf']
Unique values in column 'Gender': ['Sex Not Available' 'Male' 'Joint' 'Female']
Unique values in column 'approv_in_adv': ['nopre' 'pre']
Unique values in column 'loan_type': ['type1' 'type2' 'type3']
Unique values in column 'loan_purpose': ['p1' 'p4' 'p3' 'p2']
Unique values in column 'Credit_Worthiness': ['l1' 'l2']
Unique values in column 'open_credit': ['nopc' 'opc']
Unique values in column 'business_or_commercial': ['nob/c' 'b/c']
Unique values in column 'rate_of_interest': [4.0454758 4.56      4.25      4.        3.99      4.5       4.125
 4.875     3.49      4.375     3.625     3.175     2.99      4.99
 5.25      3.75      3.375     3.25      2.75      3.875     3.5
 4.75      3.125     5.19      4.49      2.875     5.125     4.625
 3.7       5.        3.        5.375     4.18      3.69      5.5
 3.65      5.75      3.775     3.56      5.625     6.24      4.475
 3.4       2.925     3.925     5.74      5.875     3.45      4.275
 2.975     3.725     2.85      3.675     3.55      3.93      2.375
 3.85      3.525     2.725     2.5       2.6       5.99      5.49
 8.        3.025     3.8       2.775     3.05      3.325     6.
 3.825     3.15      3.1       4.4       3.3       4.05      6.75
 4.025     3.475     2.625     3.225     3.575     4.175     3.9
 2.95      3.075     3.275     7.        3.425     5.69      5.3
 3.2       3.6       2.65      3.35      7.75      4.225     2.25
 3.95      4.7       2.125     2.8       0.        4.2       3.975
 4.075     2.675     7.375     4.44      4.865     4.15      6.125
 4.1       6.375     6.5       4.35      4.3       6.25      2.475
 4.425     4.525     7.5       4.55      4.95      4.82      6.875
 4.325     2.575     2.9       3.74      7.125     2.7      ]
Unique values in column 'Upfront_charges': [2596.45  595.      0.   ... 3113.06 1226.64 4323.33]
Unique values in column 'term': [360. 300. 180. 312. 144. 240. 348. 324. 120.  96. 192. 156. 228. 336.
 288. 108. 276. 132. 216. 168. 204. 264. 252. 165. 280. 322.]
Unique values in column 'Neg_ammortization': ['not_neg' 'neg_amm']
Unique values in column 'interest_only': ['not_int' 'int_only']
Unique values in column 'lump_sum_payment': ['not_lpsm' 'lpsm']
Unique values in column 'property_value': [1.1800e+05 4.1800e+05 5.0800e+05 6.5800e+05 7.5800e+05 1.0080e+06
 4.3800e+05 3.0800e+05 4.7800e+05 6.8800e+05 1.6800e+05 7.0800e+05
 2.5800e+05 2.9800e+05 1.3800e+05 3.6800e+05 5.9800e+05 7.4800e+05
 5.5800e+05 1.9800e+05 4.4800e+05 4.2800e+05 5.6800e+05 2.1800e+05
 4.6800e+05 2.2800e+05 3.1800e+05 3.3800e+05 5.3800e+05 4.0800e+05
 1.0180e+06 1.1080e+06 5.2800e+05 2.4800e+05 1.5080e+06 6.0800e+05
 6.6800e+05 8.0800e+05 9.4800e+05 1.2800e+05 2.3800e+05 7.1800e+05
 8.8800e+05 1.4800e+05 6.2800e+05 9.2800e+05 2.0800e+05 1.1980e+06
 1.8800e+05 5.8800e+05 1.3080e+06 6.7800e+05 3.5800e+05 2.8800e+05
 2.0080e+06 5.7800e+05 3.4080e+06 3.4800e+05 8.8000e+04 4.9800e+05
 8.1800e+05 7.6800e+05 3.8800e+05 6.1800e+05 8.9800e+05 2.7800e+05
 9.7800e+05 1.7080e+06 8.5800e+05 4.5800e+05 6.3800e+05 1.2080e+06
 6.4800e+05 9.0800e+05 1.1380e+06 7.9800e+05 3.7800e+05 1.5800e+05
 8.2800e+05 3.9800e+05 1.0800e+05 1.2680e+06 1.0680e+06 7.8000e+04
 4.8800e+05 1.2980e+06 5.4800e+05 7.8800e+05 5.1800e+05 9.3800e+05
 1.7800e+05 8.3800e+05 1.7580e+06 3.2800e+05 2.1280e+06 3.8480e+06
 9.9800e+05 7.3800e+05 7.7800e+05 2.3980e+06 7.2800e+05 9.8000e+04
 9.5800e+05 2.6800e+05 6.8000e+04 8.7800e+05 6.9800e+05 2.6080e+06
 1.0480e+06 9.8800e+05 8.4800e+05 8.6800e+05 1.5380e+06 2.3080e+06
 1.9480e+06 1.2580e+06 1.1280e+06 1.3380e+06 1.0280e+06 1.2280e+06
 1.0880e+06 1.1680e+06 1.4680e+06 1.1580e+06 9.1800e+05 3.1080e+06
 1.9080e+06 1.2180e+06 1.0780e+06 1.0380e+06 1.3680e+06 1.2380e+06
 2.7880e+06 1.0580e+06 1.4380e+06 1.1480e+06 1.0980e+06 1.4880e+06
 2.5980e+06 1.8080e+06 1.6580e+06 1.4180e+06 2.1080e+06 1.3580e+06
 5.8080e+06 1.6480e+06 9.6800e+05 2.8780e+06 1.4280e+06 1.5180e+06
 3.8080e+06 1.6080e+06 2.0780e+06 1.2480e+06 1.2780e+06 3.3080e+06
 1.5680e+06 1.4080e+06 2.2080e+06 1.3280e+06 1.1780e+06 1.3780e+06
 1.9980e+06 5.8000e+04 1.1180e+06 4.8000e+04 2.5080e+06 1.5280e+06
 1.2880e+06 2.0580e+06 1.4480e+06 1.5580e+06 1.5780e+06 3.2580e+06
 3.8000e+04 2.8080e+06 1.7980e+06 1.8280e+06 5.2580e+06 1.8680e+06
 1.4580e+06 1.7280e+06 2.4580e+06 1.8880e+06 5.2080e+06 1.6280e+06
 1.5480e+06 4.4380e+06 6.4080e+06 1.9580e+06 1.6780e+06 1.5880e+06
 1.3180e+06 1.1880e+06 1.7780e+06 3.5680e+06 2.2580e+06 2.1580e+06
 2.6180e+06 2.4080e+06 3.0080e+06 3.2080e+06 1.6180e+06 2.7080e+06
 1.4780e+06 6.5080e+06 3.3680e+06 3.0780e+06 1.7880e+06 2.4780e+06
 4.3580e+06 3.5580e+06 2.4880e+06 4.2080e+06 2.5580e+06 3.5080e+06
 3.6580e+06 2.4980e+06 1.6680e+06 3.0680e+06 2.6880e+06 2.9080e+06
 1.7180e+06 1.7380e+06 1.7480e+06 1.3880e+06 1.3980e+06 1.8580e+06
 1.9680e+06 2.2280e+06 1.9880e+06 1.6380e+06 2.8980e+06 1.3480e+06
 3.1280e+06 2.3580e+06 3.1980e+06 2.5880e+06 3.6880e+06 4.0080e+06
 3.0980e+06 2.2980e+06 1.8380e+06 1.6980e+06 2.4180e+06 4.8780e+06
 4.5080e+06 1.9780e+06 3.9080e+06 8.0000e+03 1.6508e+07 1.4980e+06
 5.0080e+06 4.4980e+06 2.0480e+06 2.1780e+06 1.5980e+06 1.6880e+06
 2.1980e+06 2.7580e+06 3.1580e+06 2.0380e+06 2.3280e+06 3.8180e+06
 2.8380e+06 5.3080e+06 2.6780e+06 2.7180e+06 2.0280e+06 2.4280e+06
 1.9180e+06 2.5280e+06 2.2680e+06 2.8000e+04 4.4580e+06 2.5480e+06
 2.9480e+06 2.8580e+06 1.7680e+06 1.8780e+06 4.4080e+06 3.5780e+06
 2.2180e+06 1.9280e+06 3.2980e+06 3.8580e+06 2.3380e+06 4.7780e+06
 1.8180e+06 4.6080e+06 3.2180e+06 3.2680e+06 1.8480e+06 2.0980e+06
 2.8880e+06 2.6580e+06 3.2280e+06 2.5680e+06 2.6280e+06 4.2580e+06
 1.1008e+07 6.9080e+06 3.0180e+06 2.3780e+06 1.8980e+06 2.8180e+06
 3.4880e+06 2.3180e+06 2.9680e+06 4.7580e+06 2.3880e+06 3.7880e+06
 2.1180e+06 5.5080e+06 3.0280e+06 2.2380e+06 4.1580e+06 1.9380e+06
 2.9280e+06 5.7580e+06 2.2780e+06 3.8780e+06 4.0580e+06 2.1480e+06
 4.6480e+06 2.9580e+06 2.3680e+06 3.0580e+06 3.4280e+06 2.5380e+06
 2.9380e+06 6.0580e+06 3.4580e+06 2.4680e+06 2.4380e+06 4.2180e+06
 2.1880e+06 3.2780e+06 3.3780e+06 2.0880e+06 2.8480e+06 2.5780e+06
 2.1380e+06 4.4480e+06 2.6680e+06 4.0880e+06 4.1080e+06 3.0380e+06
 6.1080e+06 4.4280e+06 2.7280e+06 8.5080e+06 3.7080e+06 3.0880e+06
 1.2008e+07 4.6580e+06 2.7780e+06 1.0008e+07 3.1680e+06 3.6080e+06
 2.5180e+06 2.0680e+06 3.7780e+06 5.0580e+06 4.5580e+06 3.7680e+06
 2.0180e+06 2.7680e+06 2.8280e+06 6.2080e+06 4.2880e+06 7.6080e+06
 2.4480e+06 3.6780e+06 3.9680e+06 9.2680e+06 2.6380e+06 4.9080e+06
 3.3280e+06 3.7280e+06 4.9180e+06 1.8000e+04 3.1780e+06 2.3480e+06
 2.6980e+06]
Unique values in column 'construction_type': ['sb' 'mh']
Unique values in column 'occupancy_type': ['pr' 'sr' 'ir']
Unique values in column 'Secured_by': ['home' 'land']
Unique values in column 'total_units': ['1U' '2U' '3U' '4U']
Unique values in column 'income': [ 1740.  4980.  9480. ... 72060. 78720. 79920.]
Unique values in column 'credit_type': ['EXP' 'EQUI' 'CRIF' 'CIB']
Unique values in column 'Credit_Score': [758 552 834 587 602 864 860 863 580 788 723 501 884 520 773 685 846 534
 629 688 668 692 620 533 518 812 647 683 705 701 591 889 651 716 780 799
 766 868 765 673 876 886 772 640 798 858 543 555 603 808 519 786 769 556
 567 632 818 584 750 838 741 820 665 783 663 612 739 571 870 793 804 801
 711 634 764 865 593 511 677 774 638 644 732 586 642 872 898 734 639 506
 664 670 577 857 653 595 787 560 613 514 867 717 619 600 524 883 503 887
 604 648 797 806 845 815 585 729 538 791 671 572 755 760 578 836 900 777
 667 880 568 805 590 892 540 869 737 831 608 803 795 674 781 545 796 660
 850 851 794 866 611 621 862 829 848 775 733 700 633 702 882 686 652 844
 649 557 761 569 523 740 690 616 782 601 809 855 768 627 854 762 746 592
 703 697 710 522 789 693 597 680 575 694 581 678 714 871 800 853 718 713
 874 625 626 500 695 517 759 792 822 516 704 605 539 598 763 515 508 529
 830 551 715 802 879 743 699 617 661 896 856 861 767 656 875 778 893 785
 779 565 753 852 719 744 770 614 888 547 728 618 574 505 807 530 814 843
 635 824 559 837 847 885 630 589 654 724 527 738 811 546 537 594 658 583
 666 742 512 877 706 727 698 609 623 544 645 657 712 513 771 736 536 828
 588 730 731 646 563 525 784 725 752 756 833 561 570 899 890 720 722 526
 553 596 549 709 735 776 881 669 726 535 745 636 684 827 672 573 816 707
 607 817 873 810 679 558 624 825 708 502 659 757 599 749 894 541 675 615
 641 682 628 582 832 550 528 509 821 849 691 826 662 504 676 579 689 622
 721 835 532 751 748 610 754 878 823 562 548 631 637 606 687 564 696 819
 839 840 747 681 566 891 790 897 542 813 859 650 842 521 841 531 643 655
 507 576 510 554 895]
Unique values in column 'co-applicant_credit_type': ['CIB' 'EXP']
Unique values in column 'age': ['25-34' '55-64' '35-44' '45-54' '65-74' '>74' '<25']
Unique values in column 'submission_of_application': ['to_inst' 'not_inst']
Unique values in column 'LTV': [ 98.72881356  75.13586957  80.01968504 ... 151.8145161   41.49550706
  32.80201342]
Unique values in column 'Region': ['south' 'North' 'central' 'North-East']
Unique values in column 'Security_Type': ['direct' 'Indriect']
Unique values in column 'Status': [1 0]
Unique values in column 'dtir1': [45. 39. 46. 42. 40. 44. 30. 36. 51. 20. 31.  6. 35. 34. 49. 37. 41. 38.
 56. 23. 28. 11. 27. 55. 22. 24. 52. 33. 26. 47. 60. 25. 32. 10. 15. 53.
  7. 19. 48. 59. 57.  9. 50. 21. 58. 29. 43. 17. 54. 13. 12. 16. 61. 18.
 14.  8.  5.]

In [16]:
data2.head()

,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,rate_of_interest,Upfront_charges,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,4.045476,2596.45,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,cf,Male,nopre,type2,p1,l1,nopc,b/c,4.045476,2596.45,...,EQUI,552,EXP,55-64,to_inst,75.135870,North,direct,1,39.0
2,cf,Male,pre,type1,p1,l1,nopc,nob/c,4.560000,595.00,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,cf,Male,nopre,type1,p4,l1,nopc,nob/c,4.250000,2596.45,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,cf,Joint,pre,type1,p1,l1,nopc,nob/c,4.000000,0.00,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0

In [17]:
data2=pd.get_dummies(data2)
data2.head()

,rate_of_interest,Upfront_charges,term,property_value,income,Credit_Score,LTV,Status,dtir1,loan_limit_cf,...,age_<25,age_>74,submission_of_application_not_inst,submission_of_application_to_inst,Region_North,Region_North-East,Region_central,Region_south,Security_Type_Indriect,Security_Type_direct
0,4.045476,2596.45,360.0,118000.0,1740.0,758,98.728814,1,45.0,True,...,False,False,False,True,False,False,False,True,False,True
1,4.045476,2596.45,360.0,418000.0,4980.0,552,75.135870,1,39.0,True,...,False,False,False,True,True,False,False,False,False,True
2,4.560000,595.00,360.0,508000.0,9480.0,834,80.019685,0,46.0,True,...,False,False,False,True,False,False,False,True,False,True
3,4.250000,2596.45,360.0,658000.0,11880.0,587,69.376900,0,42.0,True,...,False,False,True,False,True,False,False,False,False,True
4,4.000000,0.00,360.0,758000.0,10440.0,602,91.886544,0,39.0,True,...,False,False,True,False,True,False,False,False,False,True

In [18]:
data

,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,rate_of_interest,Upfront_charges,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,4.045476,2596.45,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,cf,Male,nopre,type2,p1,l1,nopc,b/c,4.045476,2596.45,...,EQUI,552,EXP,55-64,to_inst,75.135870,North,direct,1,39.0
2,cf,Male,pre,type1,p1,l1,nopc,nob/c,4.560000,595.00,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,cf,Male,nopre,type1,p4,l1,nopc,nob/c,4.250000,2596.45,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,cf,Joint,pre,type1,p1,l1,nopc,nob/c,4.000000,0.00,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148665,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,3.125000,9960.00,...,CIB,659,EXP,55-64,to_inst,71.792763,south,direct,0,48.0
148666,cf,Male,nopre,type1,p1,l1,nopc,nob/c,5.190000,0.00,...,CIB,569,CIB,25-34,not_inst,74.428934,south,direct,0,15.0
148667,cf,Male,nopre,type1,p4,l1,nopc,nob/c,3.125000,1226.64,...,CIB,702,EXP,45-54,not_inst,61.332418,North,direct,0,49.0
148668,cf,Female,nopre,type1,p4,l1,nopc,nob/c,3.500000,4323.33,...,EXP,737,EXP,55-64,to_inst,70.683453,North,direct,0,29.0
148669,cf,Female,nopre,type1,p3,l1,nopc,nob/c,4.375000,6000.00,...,CIB,830,CIB,45-54,not_inst,72.849462,North,direct,0,44.0

In [19]:
data2.columns

Index(['rate_of_interest', 'Upfront_charges', 'term', 'property_value',
       'income', 'Credit_Score', 'LTV', 'Status', 'dtir1', 'loan_limit_cf',
       'loan_limit_ncf', 'Gender_Female', 'Gender_Joint', 'Gender_Male',
       'Gender_Sex Not Available', 'approv_in_adv_nopre', 'approv_in_adv_pre',
       'loan_type_type1', 'loan_type_type2', 'loan_type_type3',
       'loan_purpose_p1', 'loan_purpose_p2', 'loan_purpose_p3',
       'loan_purpose_p4', 'Credit_Worthiness_l1', 'Credit_Worthiness_l2',
       'open_credit_nopc', 'open_credit_opc', 'business_or_commercial_b/c',
       'business_or_commercial_nob/c', 'Neg_ammortization_neg_amm',
       'Neg_ammortization_not_neg', 'interest_only_int_only',
       'interest_only_not_int', 'lump_sum_payment_lpsm',
       'lump_sum_payment_not_lpsm', 'construction_type_mh',
       'construction_type_sb', 'occupancy_type_ir', 'occupancy_type_pr',
       'occupancy_type_sr', 'Secured_by_home', 'Secured_by_land',
       'total_units_1U', 'total_units_2U', 'total_units_3U', 'total_units_4U',
       'credit_type_CIB', 'credit_type_CRIF', 'credit_type_EQUI',
       'credit_type_EXP', 'co-applicant_credit_type_CIB',
       'co-applicant_credit_type_EXP', 'age_25-34', 'age_35-44', 'age_45-54',
       'age_55-64', 'age_65-74', 'age_<25', 'age_>74',
       'submission_of_application_not_inst',
       'submission_of_application_to_inst', 'Region_North',
       'Region_North-East', 'Region_central', 'Region_south',
       'Security_Type_Indriect', 'Security_Type_direct'],
      dtype='object')

In [20]:
object_columns = data.select_dtypes(include=['object'])
print(object_columns)

       loan_limit             Gender approv_in_adv loan_type loan_purpose  \
0              cf  Sex Not Available         nopre     type1           p1
1              cf               Male         nopre     type2           p1
2              cf               Male           pre     type1           p1
3              cf               Male         nopre     type1           p4
4              cf              Joint           pre     type1           p1
...           ...                ...           ...       ...          ...
148665         cf  Sex Not Available         nopre     type1           p3
148666         cf               Male         nopre     type1           p1
148667         cf               Male         nopre     type1           p4
148668         cf             Female         nopre     type1           p4
148669         cf             Female         nopre     type1           p3

       Credit_Worthiness open_credit business_or_commercial Neg_ammortization  \
0                     l1        nopc                  nob/c           not_neg
1                     l1        nopc                    b/c           not_neg
2                     l1        nopc                  nob/c           neg_amm
3                     l1        nopc                  nob/c           not_neg
4                     l1        nopc                  nob/c           not_neg
...                  ...         ...                    ...               ...
148665                l1        nopc                  nob/c           not_neg
148666                l1        nopc                  nob/c           not_neg
148667                l1        nopc                  nob/c           not_neg
148668                l1        nopc                  nob/c           not_neg
148669                l1        nopc                  nob/c           not_neg

       interest_only  ... construction_type occupancy_type Secured_by  \
0            not_int  ...                sb             pr       home
1            not_int  ...                sb             pr       home
2            not_int  ...                sb             pr       home
3            not_int  ...                sb             pr       home
4            not_int  ...                sb             pr       home
...              ...  ...               ...            ...        ...
148665       not_int  ...                sb             pr       home
148666       not_int  ...                sb             ir       home
148667       not_int  ...                sb             pr       home
148668       not_int  ...                sb             pr       home
148669       not_int  ...                sb             pr       home

       total_units credit_type co-applicant_credit_type    age  \
0               1U         EXP                      CIB  25-34
1               1U        EQUI                      EXP  55-64
2               1U         EXP                      CIB  35-44
3               1U         EXP                      CIB  45-54
4               1U        CRIF                      EXP  25-34
...            ...         ...                      ...    ...
148665          1U         CIB                      EXP  55-64
148666          4U         CIB                      CIB  25-34
148667          1U         CIB                      EXP  45-54
148668          1U         EXP                      EXP  55-64
148669          1U         CIB                      CIB  45-54

       submission_of_application Region Security_Type
0                        to_inst  south        direct
1                        to_inst  North        direct
2                        to_inst  south        direct
3                       not_inst  North        direct
4                       not_inst  North        direct
...                          ...    ...           ...
148665                   to_inst  south        direct
148666                  not_inst  south        direct
148667                  not_inst  North        direct
148668                   to_inst  North        direct
148669                  not_inst  North        direct

[148670 rows x 21 columns]

In [21]:
for i in [ 'loan_limit_cf',
       'loan_limit_ncf', 'Gender_Female', 'Gender_Joint', 'Gender_Male',
       'Gender_Sex Not Available', 'approv_in_adv_nopre', 'approv_in_adv_pre',
       'loan_type_type1', 'loan_type_type2', 'loan_type_type3',
       'loan_purpose_p1', 'loan_purpose_p2', 'loan_purpose_p3',
       'loan_purpose_p4', 'Credit_Worthiness_l1', 'Credit_Worthiness_l2',
       'open_credit_nopc', 'open_credit_opc', 'business_or_commercial_b/c',
       'business_or_commercial_nob/c', 'Neg_ammortization_neg_amm',
       'Neg_ammortization_not_neg', 'interest_only_int_only',
       'interest_only_not_int', 'lump_sum_payment_lpsm',
       'lump_sum_payment_not_lpsm', 'construction_type_mh',
       'construction_type_sb', 'occupancy_type_ir', 'occupancy_type_pr',
       'occupancy_type_sr', 'Secured_by_home', 'Secured_by_land',
       'total_units_1U', 'total_units_2U', 'total_units_3U', 'total_units_4U',
       'credit_type_CIB', 'credit_type_CRIF', 'credit_type_EQUI',
       'credit_type_EXP', 'co-applicant_credit_type_CIB',
       'co-applicant_credit_type_EXP', 'age_25-34', 'age_35-44', 'age_45-54',
       'age_55-64', 'age_65-74', 'age_<25', 'age_>74',
       'submission_of_application_not_inst',
       'submission_of_application_to_inst', 'Region_North',
       'Region_North-East', 'Region_central', 'Region_south',
       'Security_Type_Indriect', 'Security_Type_direct']:
       data2[i]=data2[i].astype('int64')

In [22]:
data2.head()

,rate_of_interest,Upfront_charges,term,property_value,income,Credit_Score,LTV,Status,dtir1,loan_limit_cf,...,age_<25,age_>74,submission_of_application_not_inst,submission_of_application_to_inst,Region_North,Region_North-East,Region_central,Region_south,Security_Type_Indriect,Security_Type_direct
0,4.045476,2596.45,360.0,118000.0,1740.0,758,98.728814,1,45.0,1,...,0,0,0,1,0,0,0,1,0,1
1,4.045476,2596.45,360.0,418000.0,4980.0,552,75.135870,1,39.0,1,...,0,0,0,1,1,0,0,0,0,1
2,4.560000,595.00,360.0,508000.0,9480.0,834,80.019685,0,46.0,1,...,0,0,0,1,0,0,0,1,0,1
3,4.250000,2596.45,360.0,658000.0,11880.0,587,69.376900,0,42.0,1,...,0,0,1,0,1,0,0,0,0,1
4,4.000000,0.00,360.0,758000.0,10440.0,602,91.886544,0,39.0,1,...,0,0,1,0,1,0,0,0,0,1

Min Max Scaling

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
x=data2.drop('Status',axis=1)
y=data2['Status']

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [27]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4119003822992021

In [28]:
x1=x.copy()
x1.columns

Index(['rate_of_interest', 'Upfront_charges', 'term', 'property_value',
       'income', 'Credit_Score', 'LTV', 'dtir1', 'loan_limit_cf',
       'loan_limit_ncf', 'Gender_Female', 'Gender_Joint', 'Gender_Male',
       'Gender_Sex Not Available', 'approv_in_adv_nopre', 'approv_in_adv_pre',
       'loan_type_type1', 'loan_type_type2', 'loan_type_type3',
       'loan_purpose_p1', 'loan_purpose_p2', 'loan_purpose_p3',
       'loan_purpose_p4', 'Credit_Worthiness_l1', 'Credit_Worthiness_l2',
       'open_credit_nopc', 'open_credit_opc', 'business_or_commercial_b/c',
       'business_or_commercial_nob/c', 'Neg_ammortization_neg_amm',
       'Neg_ammortization_not_neg', 'interest_only_int_only',
       'interest_only_not_int', 'lump_sum_payment_lpsm',
       'lump_sum_payment_not_lpsm', 'construction_type_mh',
       'construction_type_sb', 'occupancy_type_ir', 'occupancy_type_pr',
       'occupancy_type_sr', 'Secured_by_home', 'Secured_by_land',
       'total_units_1U', 'total_units_2U', 'total_units_3U', 'total_units_4U',
       'credit_type_CIB', 'credit_type_CRIF', 'credit_type_EQUI',
       'credit_type_EXP', 'co-applicant_credit_type_CIB',
       'co-applicant_credit_type_EXP', 'age_25-34', 'age_35-44', 'age_45-54',
       'age_55-64', 'age_65-74', 'age_<25', 'age_>74',
       'submission_of_application_not_inst',
       'submission_of_application_to_inst', 'Region_North',
       'Region_North-East', 'Region_central', 'Region_south',
       'Security_Type_Indriect', 'Security_Type_direct'],
      dtype='object')

In [29]:
x1.drop(['loan_limit_cf',
       'loan_limit_ncf', 'Gender_Female', 'Gender_Joint', 'Gender_Male',
       'Gender_Sex Not Available', 'approv_in_adv_nopre', 'approv_in_adv_pre',
       'loan_type_type1', 'loan_type_type2', 'loan_type_type3',
       'loan_purpose_p1', 'loan_purpose_p2', 'loan_purpose_p3',
       'loan_purpose_p4', 'Credit_Worthiness_l1', 'Credit_Worthiness_l2',
       'open_credit_nopc', 'open_credit_opc', 'business_or_commercial_b/c',
       'business_or_commercial_nob/c', 'Neg_ammortization_neg_amm',
       'Neg_ammortization_not_neg', 'interest_only_int_only',
       'interest_only_not_int', 'lump_sum_payment_lpsm',
       'lump_sum_payment_not_lpsm', 'construction_type_mh',
       'construction_type_sb', 'occupancy_type_ir', 'occupancy_type_pr',
       'occupancy_type_sr', 'Secured_by_home', 'Secured_by_land',
       'total_units_1U', 'total_units_2U', 'total_units_3U', 'total_units_4U',
       'credit_type_CIB', 'credit_type_CRIF', 'credit_type_EQUI',
       'credit_type_EXP', 'co-applicant_credit_type_CIB',
       'co-applicant_credit_type_EXP', 'age_25-34', 'age_35-44', 'age_45-54',
       'age_55-64', 'age_65-74', 'age_<25', 'age_>74',
       'submission_of_application_not_inst',
       'submission_of_application_to_inst', 'Region_North',
       'Region_North-East', 'Region_central', 'Region_south',
       'Security_Type_Indriect', 'Security_Type_direct'],axis=1,inplace=True)

In [30]:
x1.head()

,rate_of_interest,Upfront_charges,term,property_value,income,Credit_Score,LTV,dtir1
0,4.045476,2596.45,360.0,118000.0,1740.0,758,98.728814,45.0
1,4.045476,2596.45,360.0,418000.0,4980.0,552,75.135870,39.0
2,4.560000,595.00,360.0,508000.0,9480.0,834,80.019685,46.0
3,4.250000,2596.45,360.0,658000.0,11880.0,587,69.376900,42.0
4,4.000000,0.00,360.0,758000.0,10440.0,602,91.886544,39.0

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x1=scaler.fit_transform(x1)

In [32]:
type(x1)

numpy.ndarray

In [33]:
x1= pd.DataFrame(x1,columns=['rate_of_interest','Upfront_charges', 'term','property_value','income','Credit_Score','LTV','dtir1'])

In [34]:
x1.head()

,rate_of_interest,Upfront_charges,term,property_value,income,Credit_Score,LTV,dtir1
0,0.505684,0.043274,1.0,0.006667,0.003007,0.6450,0.012485,0.714286
1,0.505684,0.043274,1.0,0.024848,0.008607,0.1300,0.009472,0.607143
2,0.570000,0.009917,1.0,0.030303,0.016385,0.8350,0.010096,0.732143
3,0.531250,0.043274,1.0,0.039394,0.020533,0.2175,0.008737,0.660714
4,0.500000,0.000000,1.0,0.045455,0.018044,0.2550,0.011611,0.607143

In [35]:
x2=x.drop(['rate_of_interest','Upfront_charges', 'term','property_value','income','Credit_Score','LTV','dtir1'],axis=1)
x=pd.concat([x1,x2],axis=1)
x.head()

,rate_of_interest,Upfront_charges,term,property_value,income,Credit_Score,LTV,dtir1,loan_limit_cf,loan_limit_ncf,...,age_<25,age_>74,submission_of_application_not_inst,submission_of_application_to_inst,Region_North,Region_North-East,Region_central,Region_south,Security_Type_Indriect,Security_Type_direct
0,0.505684,0.043274,1.0,0.006667,0.003007,0.6450,0.012485,0.714286,1,0,...,0,0,0,1,0,0,0,1,0,1
1,0.505684,0.043274,1.0,0.024848,0.008607,0.1300,0.009472,0.607143,1,0,...,0,0,0,1,1,0,0,0,0,1
2,0.570000,0.009917,1.0,0.030303,0.016385,0.8350,0.010096,0.732143,1,0,...,0,0,0,1,0,0,0,1,0,1
3,0.531250,0.043274,1.0,0.039394,0.020533,0.2175,0.008737,0.660714,1,0,...,0,0,1,0,1,0,0,0,0,1
4,0.500000,0.000000,1.0,0.045455,0.018044,0.2550,0.011611,0.607143,1,0,...,0,0,1,0,1,0,0,0,0,1

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [37]:
lr.fit(x_train,y_train)

LinearRegression()

In [38]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.3360262874867104

In [39]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(max_iter=1000)

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [41]:
model1=lg.fit(x_train,y_train)

In [42]:
y_pred_lg=lg.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [44]:
confusion_matrix(y_test,y_pred_lg)

array([[22271,   223],
       [ 3719,  3521]])

In [45]:
y_pred_lg

array([0, 0, 0, ..., 1, 0, 1])

In [46]:
print("Accuracy = ",accuracy_score(y_test,y_pred_lg))
print("Precision = ",precision_score(y_test,y_pred_lg))
print("Recall = ",recall_score(y_test,y_pred_lg))
print("F1 score = ",f1_score(y_test,y_pred_lg))

Accuracy =  0.8674244972085827
Precision =  0.9404380341880342
Recall =  0.48632596685082874
F1 score =  0.6411143481427531

In [47]:
#Decision Tree

In [48]:
from sklearn.tree import DecisionTreeClassifier
dt_clf=DecisionTreeClassifier(random_state=42)
dt_clf.fit(x_train,y_train)
y_pred=dt_clf.predict(x_test)

In [49]:
print("Accuraccy = ",accuracy_score(y_test,y_pred))

Accuraccy =  1.0

In [50]:
# Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier
rf_clf=RandomForestClassifier(random_state=42)
rf_clf.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [52]:
y_pred=rf_clf.predict(x_test)
print("Accuracy = ",accuracy_score(y_test,y_pred))

Accuracy =  0.9999663684670748

In [ ]:
#KNN

In [53]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
metric_k=[]
n=np.arange(3,15)
for k in n:
  clf=KNeighborsClassifier(n_neighbors=k)
  clf.fit(x_train,y_train)
  y_pred=clf.predict(x_test)
  acc=accuracy_score(y_test,y_pred)
  metric_k.append(acc)

In [ ]:
metric_k

In [ ]:
plt.plot(n,metric_k,'o-')
plt.xlabel('k Value')
plt.ylabel('Accuracy Score')
plt.grid()

In [ ]:
clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

In [ ]:
y_pred

In [ ]:
print('Accuracy = ',accuracy_score(y_test,y_pred))
print("Precision = ",precision_score(y_test,y_pred))
print("Recall = ",recall_score(y_test,y_pred))
print("F1 score = ",f1_score(y_test,y_pred))

In [ ]:
#NAIVE BAYES CLASSIFIER

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

In [ ]:
gnb.fit(x_train,y_train)

In [ ]:
y_pred_gnb=gnb.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred_gnb)

In [ ]:
y_pred_gnb

In [ ]:
print("Accuracy = ",accuracy_score(y_test,y_pred_gnb))
print("Precision = ",precision_score(y_test,y_pred_gnb))
print("Recall = ",recall_score(y_test,y_pred_gnb))
print("F1 score = ",f1_score(y_test,y_pred_gnb))